### ISSUE TITLE
Range of range reductions

### ISSUE THREAD

**Issue by wwitzel** [PyProveIt/Prove-It#170]
This relates to a bug reported in the comments of Issue #166 by @jmadridlarra .  Essentially, the cause of the bug is that singular_range_reduction cannot be applied to an "f" that is an ExprRange since we cannot perform operation replacement using a lambda whose body is an ExprRange (this restriction is needed to maintain arities and tuple lengths).  We need a different way to effect effect such reductions.  @jmadridlarra is using a temporary work-around.  For his purposes, he just needs to ensure that auto-reduction is disabled to avoid his error.  But a better solution is to fix this so that range reductions for ranges of ranges (both singular and empty range reductions) can be properly performed.

**Comment by jmadridlarra** [comment]
By adding a range reduction theorem for both a singular range of ranges and an empty range of ranges, we should be able to resolve this issue:

![image](https://user-images.githubusercontent.com/51240353/89924747-b0394080-dbbf-11ea-920d-3398d67dc1be.png)

![image](https://user-images.githubusercontent.com/51240353/89924804-c1824d00-dbbf-11ea-996a-a25f249abf9c.png)

Additionally, I added a "nested_range_reduction" theorem which would reduce a nested range to a range:

![image](https://user-images.githubusercontent.com/51240353/89925069-1f169980-dbc0-11ea-8d06-f1fb3c205f11.png)

I'm a bit hesitant about the "a" in the rhs of the equality, but let me know your thoughts on this extra theorem.

**Comment by wwitzel** [comment]
nested_range_reduction is not right.  I think you would want:
(f(m, i), ..., f(m, j), ......, f(m, i), ..., f(m, j)) = (f(m, i), ..., f(m, j))
singular_nested_range_reduction is just a special case of this.  In fact, I think what I have here should be singular_nested_range_reduction and you don't need your other version.

**Comment by wwitzel** [comment]
@jmadridlarra also asked a question in e-mail about how to instantiate "f" in for the nested version of ExprRange.singular_nested_range_reduction .   You should use
f : expr_range.lambda_map.lambda_map.
Does that answer your question?

**Comment by jmadridlarra** [comment]
That makes sense.  In the _possibly_reduced_range_entries method in expr_range.py, would Prove-It know to use singular_range_reduction after using singular_nested_range_reduction to reduce something like A_{1, 1}...A_{1, 1}......A_{1, 1}...A_{1, 1} to A_{1, 1}?  Or does that have to be explicitly implemented?  

Yes, using f:expr_range.lambda_map.lambda_map is what I needed.  Thank you.

**Comment by wwitzel** [comment]
I see your point regarding singular_nested_range_reduction.  Maybe you do want a separate theorem for that special case.  Otherwise, you'd have to two theorem to reduce it fully.  Having the special case theorem makes sense to me now.  Naming them is the tricky part.

Regarding "empty_range_of_range_def", I usually only use "def" in the names of axioms.  Also, we can make that stronger my using a disjunction of the conditions rather than a conjunction.  It is an empty range whether the internal ranges are empty or the external range is empty.

**Comment by wwitzel** [comment]
Actually, I changed my mind again.  You may not need that special case.  It should reduce the internal ExprRange automatically.  I'm not sure.  You'll have to test the various combinations of inner vs. outer reductions.  You may just need two theorems.  Try that first.

**Comment by jmadridlarra** [comment]
Okay, I'll try it first with just the two theorems you mentioned first.  
![image](https://user-images.githubusercontent.com/51240353/89934830-6c016c80-dbce-11ea-8dac-e8a48a45cbf8.png)

![image](https://user-images.githubusercontent.com/51240353/89934944-95ba9380-dbce-11ea-8af4-41a5b751956c.png)

expr_range.lambda_map.lambda_map threw an error, I ended up using expr_range.lambda_expr.**body**.lambda_map:

![image](https://user-images.githubusercontent.com/51240353/89935198-0a8dcd80-dbcf-11ea-9039-959627f18d41.png)

 but is this what you intended?  

Either way, when I instantiated the theorem I got this error:

**LambdaApplicationError: Failure to apply j -> a_{i,j} to (_a, b):
Too many arguments**

**Comment by wwitzel** [comment]
Ah, I see.  We need to map
(i, j) -> a_{i, j}
So we really want to create the Lambda that with the inner and outer parameters.  Something like:
lambda_map = Lambda((expr_range.parameter, expr_range.body.parameter), expr_range.body.body)

(By the way, expr_range.body is the same as expr_range.lambda_map.body.)

**Comment by jmadridlarra** [comment]
_ possibly_reduced_range_entries() is correctly reducing the singular_nested_range_reduction for both test cases:

![image](https://user-images.githubusercontent.com/51240353/89944598-55aedd00-dbdd-11ea-8d61-70c7d0982490.png)

However, I have been unable to successfully compute the length of an empty_range_of_range.  The instantiation works just fine and the code seems to be doing everything correctly:

![image](https://user-images.githubusercontent.com/51240353/89951138-1934ae80-dbe8-11ea-8dcd-9d54849366fb.png)

The print statements show that it is reaching the correct theorem and print out the instantiated theorem... and then move on to another expression that needs to be reduced.  However, this is the error message:

![image](https://user-images.githubusercontent.com/51240353/89951264-56993c00-dbe8-11ea-8751-071cad1c8591.png)

Now this makes sense because 1 - 2 + 1 evaluates to 0 and 0 is not in the positive naturals...right? Earlier in the error output, Prove-It is unable to prove that 0 is in the positive naturals:

![image](https://user-images.githubusercontent.com/51240353/89951406-93fdc980-dbe8-11ea-83a6-0786d0a51827.png)

For some reason, Prove-It is trying to instantiate the len_of_ranges_with_repeated_indices theorem:

![image](https://user-images.githubusercontent.com/51240353/89951609-f951ba80-dbe8-11ea-87a4-603d0747b178.png)

But because n is zero in this case, it is throwing an error.  Ideally we would want Prove-It to reduce this to an empty ExprTuple and then realize that the length is zero before it tries to instantiate this theorem, right?

**Comment by jmadridlarra** [comment]
After a phone conversation with @wwitzel, we decided to add another theorem for the special case where n is zero.  However, in order to make this "special case" more general, I created the following theorem:

len_of_empty_ranges_with_repeated_indices = Forall((m, n), Forall((varRange(f, m, n), i, j),
                                         Equals(Len(ExprRange(k, fk_i_to_j, m, n)),
                                           zero).withWrapBeforeOperator()), 
                                              domain=Naturals, conditions=[Equals(Add(n, one), m)])

However, this theorem throws an error:

ParameterCollisionError: Parameter variables may not occur as free variables in parameter indices.  (`_f_{_g}, .._f_{_b}.., _f_{_f}, _e, _d`) does not satisfy this criterion. 

The error makes sense because _f is appearing twice, however, they are both dummy variables, right?  How does one avoid repeated dummy variables?  

I thought about going back to the specific example where m was one and n was zero, but then we don't have a theorem for an empty range that starts at four and ends at 3, for example.  On that note, what about an empty range that starts at four and ends at two?  As I'm thinking about this further, maybe I don't completely understand the subscript for f.  Is it assumed that f would always start at 1, because that is how we count the individual items?  Are the examples that I suggested above feasible examples?

**Comment by wwitzel** [comment]
That's a strange error.  I'm looking into it.

**Comment by wwitzel** [comment]
Okay, I think I fixed that bug.  I just need to decide how to commit it (what branch).  I'll let you know.  But it did occur to me that your planned theorem won't cover all cases of computing the length where there is a reduction.  We either need more general theorems, more like "general_len" or we need to implement the other idea where we substitute the reduction into the Len.

**Comment by jmadridlarra** [comment]
I'm intrigued by the other cases that will not be covered. I thought that this generic theorem, in conjunction with the other two, would take care of most of the reductions, but if you think there are more theorems that should be added, maybe it would be best to just move forward with substituting the reduction into the Len.  It's your call.

**Comment by jmadridlarra** [comment]
Because we didn't come to a concrete conclusion regarding the creation of a theorem (moreover what that theorem would be), I went ahead with a temporary fix by changing both len_of_ranges_with_repeated_indices and len_of_ranges_with_repeated_indices_from_1 to place n in the Naturals set, rather than the NaturalsPos set.  This seemed to solve the zero issue, however, now it seems like I am running into reduction errors.  

Len(ExprRange(i, ExprRange(j, indexed_var(a, [i, j]), one, n), one, zero)).computation(assumptions=[InSet(n, Naturals)])  

This case, where the outer range is going from one to zero, is throwing the following error:

`InstantiationFailure: Proof step failed assuming {n in Naturals}:`
`Attempting to instantiate |- forall_{n in Naturals} [forall_{f_{1}, ..f_{_a}.., f_{n}, i | i in Naturals} (|(f_{1}(1), ..f_{1}(x).., f_{1}(i), ....f_{k}(1), ..f_{k}(x).., f_{k}(i)...., f_{n}(1), ..f_{n}(x).., f_{n}(i))| \\  = (n * i))] with {n: 0, f: (j -> a_{1,j}, ..j -> a_{i,j}.., j -> a_{0,j}), i: n, (f_{1}, ..f_{_a}.., f_{0}): (j -> a_{1,j}, ..j -> a_{i,j}.., j -> a_{0,j})}:`
`Failure to apply (n, f_{1}, ..f_{_a}.., f_{0}, i) -> (i in Naturals) to (0, [j -> a_{1,j}], ..[j -> a_{i,j}].., [j -> a_{0,j}], n) assuming (n in Naturals,):`
`<bound method Len.doReducedEvaluation of |n|> must return an KnownTruth equality with an irreducible value on the right side, not |- |n| = |n| for |n| assuming (n in Naturals,)`

I found the `<bound method>` portion to be the most interesting since I had not seen this error before.  Len.doReducedEvaluation calls _computation()  By printing out what doReducedEvaluation was trying to compute, I discovered that it was trying to compute the length of n: |n|.  However this block of code in _computation returns a logical equality, not a knownTruth with an irreducible value on the right like the error message wanted:

       if not isinstance(self.operand, ExprTuple): 
            # Don't know how to compute the length if the operand is
            # not a tuple. For example, it could be a variable that 
            # represent a tuple.  So just return the self equality.
            from proveit.logic import Equals
            return Equals(self, self).prove()

This makes sense as far as why the error is being thrown, but how do you propose we fix it?  The comment in the block of code makes sense, but it doesn't satisfy the <bound method> error. Perhaps we need to prevent Prove-It from trying to compute the Len() of a single variable/Literal via automation?  In line 1179 of Lambda_expr.py, Prove-It is calling Len(operand).evaluation() which raises this error because the operand is "n" for some reason.

**Comment by wwitzel** [comment]
@jmadridlarra , I think this is what we need for a fully generally len_of_empty_range_of_ranges theorem:
![len_of_empty_range_of_ranges](https://user-images.githubusercontent.com/25727727/90166345-50759d80-dd57-11ea-84cb-166228140b3c.png)

It allows us to create a general range of ranges expression on the left with the only restriction that it is actually an empty range of ranges.  Note, because it is an empty external range, there are no instances of i(k) and j(k) that actually need to be constrained.  It is a weird special case because of this fact that there no actual instances of anything, but I think this is valid.

**Comment by jmadridlarra** [comment]
When I reran the proveit.core_expr_types.tuples theorem notebook today, the general_len theorem got stuck in an infinite loop.  I am thoroughly confused because general_len is before any of the new theorems I added and was running just fine before today.  Here is an excerpt of the loop:

```
c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in __init__(self, parameter_or_parameters, body, _generic_expr)
    171             try:
    172                 defaults.automation = False
--> 173                 genericExpr = self._generic_version()
    174             finally:
    175                 defaults.automation = prev_automation

c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in _generic_version(self)
    273                         relabel_map, assumptions=tuple())._generic_version()
    274                 generic_body = generic_body._generic_version()
--> 275                 return Lambda(generic_parameters, generic_body)
    276             else:
    277                 return self

c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in __init__(self, parameter_or_parameters, body, _generic_expr)
    171             try:
    172                 defaults.automation = False
--> 173                 genericExpr = self._generic_version()
    174             finally:
    175                 defaults.automation = prev_automation

c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in _generic_version(self)
    273                         relabel_map, assumptions=tuple())._generic_version()
    274                 generic_body = generic_body._generic_version()
--> 275                 return Lambda(generic_parameters, generic_body)
    276             else:
    277                 return self
```

The only differences is that I pulled in branch 172-variable-bug-fixes.  I couldn't remember if I was getting an infinite loop before I pulled in branch 172 (I thought I pulled in the branch hoping that it would fix the loop), but when I checked out the commit before the merge, the notebook ran fine.  I thought maybe I accidentally made an edit, but the only edits I have are adding theorems and print statements... no new machinery.  Any thoughts about why this error might be happening?

**Comment by wwitzel** [comment]
Yeah, I just noticed that.  I have a pretty good idea what's going on.  I'll fix it.

**Comment by wwitzel** [comment]
A temporary fix for you, @jmadridlarra , is to revert back to the previous version of lambda_expr.py.  That should work find for your purposes as long as you have the expr_range.py fix from 172-variable-bug-fixes.  I'll try to fix this soon, though, and commit it to 172-variable-bug-fixes (that's where I broke things).

**Comment by jmadridlarra** [comment]
Unfortunately, reverting to a state before the merge didn't actually fix the loop.  Everything except our new theorem from @wwitzel 's comment above (**len_of_empty_range_of_ranges**) runs smoothly.  However, this new theorem raises the infinite loop without the fixes from the 172-variable-bug-fixes.  

When I cherrypick the **expr_range.py** fix from the 172-variable-bug-fixes branch, both the general_len theorem and the len_of_ranges_with_repeated_indices theorem throw the loop instead, but len_of_empty_range_of_ranges (our new theorem) runs just fine. 

When I cherrypick the **lambda_expr.py** fix after reverting the expr_range.py fix, just the len_of_empty_range_of_ranges throws a recursion error because of the loop. 

Lastly, when I cherrypick both the expr_range.py **and** the lambda_expr.py two new theorems throw recursion errors: len_of_ranges_with_repeated_indices_from_1, tuple_eq_via_elem_eq.  Interestingly though, len_of_empty_range_of_ranges (our new theorem), len_of_ranges_with_repeated_indices, and general_len all run without error. 

I doubt this has much to do with the specific theorems, but I thought it might be relevant so I included it just in case.  As far as I could tell, all of the recursion errors were the same and stem from lambda_expr.py (from the error message I sent above).  

Sorry for the late reply, it took me quite a while to nail down exactly what was happening.

**Comment by wwitzel** [comment]
Yeah, sorry.  I've been puzzling through this myself.  I'm scratching my head right now.

**Comment by jmadridlarra** [comment]
It seems like this loop existed before your edits to 172-variable-bug-fixes, but the edits to lambda_expr.py and expr_range.py inadvertently solved it for some cases... but not all.  I think the 170-RoR_reductions origin branch is up to date if that's helpful for your debugging process.

**Comment by wwitzel** [comment]
There are a few fixes needed w.r.t. range of range instantiations.

1. A range of ranges instantiation must be linearized when applying a lambda map on the operands.  That is, when you have
x_{1,1}, ..., x_{1,n}, ......, x_{m,1}, ..., x_{m,n}
x should be instantiated to a tuple of tuples since two indices are used to access the elements of x.  But that tuple of tuples must be linearized when giving it to some mapping
(x_{1,1}, ..., x_{1,n}, ......, x_{m,1}, ..., x_{m,n}) -> f(x_{1,1}, ..., x_{1,n}, ......, x_{m,1}, ..., x_{m,n})
For example x : [[0, 1], [2, 3]] would get linearized to [0, 1, 2, 3] to be fed into the lambda map since lambda map parameters are always linearized.  This works properly for ranges, but not ranges of ranges.

2. Within lambda.apply, the linearized range of ranges instantiation must be transformed back into a tuple of tuples for a proper repl_map entry, with the associated key also being a tuple of tuples for a proper match.

3. We need to make sure this repl_map for a range of ranges is handled in a proper recursive fashion in expr_range._replaced_entries.  For this to work, it may simply be a matter of switching the order of the nested IndexedVar indices.  That is, x_{i, j} is currently implemented internally as (x_i)_j, but perhaps it should be (x_j)_i.  That way, the first index is used to index into one of many tuples.  For example, with x : [[0, 1], [2, 3]], x_{1, j} (using 1-based indexing) would correspond to [0, 1].

**Comment by wwitzel** [comment]
After a discussion with @jmadridlarra , we should add a fourth:
4. Make sure we check that the proper convention is followed when a Lambda expression is created; inner vs outer and first vs second index correspondence.

**Comment by jmadridlarra** [comment]
x_{1} ... x_{n}

x_{1, 1} ... x_{n, 1} ...... x_{1, m} ... x_{n, m}

**Comment by wwitzel** [comment]
One reason for this original convention,
x_{1,1}, ..., x_{1,n}, ......, x_{m,1}, ..., x_{m,n}
is its correspondence to counting.  But that may not be a good reason.

**Comment by jmadridlarra** [comment]
ExprRange(i, IndexedVar(x, i), one, n)

ExprRange(j, ExprRange(i, IndexedVar(x, [i, j]), one, n), one, m)

0 1
2 3

x_{1,1} => 0; x_{1,2} => 1; x_{2, 1} => 2; x_{2, 2} => 3

**Comment by wwitzel** [comment]
As I think about this more, it might work out fine to be "ambidextrous" w.r.t. row-major vs column-major order.  We could represent `x_{i, j}` as it is (not as a nested indexed variable) and just handle it appropriately in ExprRange._replaced_entries to deal with it appropriately depending on whether the range of ranges is row-major or column-major.  We should still use row-major as a convention in general, but we may be able to allow a user to have a column-major ordering of their range of ranges if they so desire.

**Comment by wwitzel** [comment]
Good news!  I seem to have steps 2 and 3 (see 8/18 comment) effectively working.  You can either use row-major ordering (our convention) or column-major ordering as long as it is consistent, so the "step 4" addendum is not necessary.  It turned out that step 2 wasn't necessary either -- it seems to work fine sticking with the linearized form.  It has been tested in tutorial2a_3_exprrange_reductions.ipynb and pushed into the 170-RoR_reductions branch.  Step 1 still remains but is not as scare as the other steps.

**Comment by wwitzel** [comment]
Also, there is no longer a need for using the weird nesting of IndexedVar's, so I'll make that change as well.  An IndexedVar will have a simple Variable base and one or more indices -- no nesting.

**Comment by wwitzel** [comment]
I pushed the updates to the 170-RoR_reductions branch.  I made the change regarding no more nesting of IndexedVars, but I change my mind regarding step 1 above.  Rather than instantiating a range of ranges of parameters with a tuple of tuples, I decided it made sense (and requires no further implementation) to instantiate it with a simple linearize (vectorized) tuple.  That is,
(x_{1,1}, ..., x_{1,n}, ......, x_{m,1}, ..., x_{m,n}) -> f(x_{1,1}, ..., x_{1,n}, ......, x_{m,1}, ..., x_{m,n})
should be instantiated like
x : [0, 1, 2, 3]
(rather than x : [[0, 1], [2, 3]]).

At least, this is what should be working at this point and is a sensible unambiguous way to do the instantiation.  We may want to revisit this later -- at least make some more appropriate error messages, but let's just try to get the quantum circuits working in this fashion for now.
