### ISSUE TITLE
ExprRanges and len(operands) vs operands.length() vs alternatives

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#192]
This issue stems from the following observations. Given an expression like this:

> theExpr = (b = b) &or; (b = a<sub>1</sub>) &or; &hellip; &or; (b = a<sub>m</sub>)

where that 2nd item in theExpr is an ExprRange, we have

> len(theExpr.operands) = 2,

giving the number of “entries” instead of the number of inferred elements, i.e. the (m+1) that someone might be hoping to get. Instead, we can use:

> theExpr.operands.length(assumptions)

to get the (m+1) or equivalent (depending on the assumptions). @wwitzel suggests this is confusing and worth considering some other options to make the distinction less confusing. @wwitzel 's  initial suggestion, still under discussion, went as follows: Perhaps we should disable __len__ so you can't do len(theExpr.operands) and make `num_entries()` and `num_elements(assumptions)` methods to be more explicit and the distinction. It could even be that trying to call `len(theExpr.operands)` gives some error message referring to the two alternative methods.

**Comment by wwitzel** [comment]
One somewhat related thing that I thought about, coming to mind after helping @jmadridlarra code up an instantiation involving ranges of parameters, is that we should try to make it so that taking a slice of a ExprTuple will return an ExprTuple.  For example:
expr.operands[:idx]
where expr in some Operation-type expression would return an ExprTuple and save the user the trouble of needing to wrap the results in an ExprTuple (e.g., before calling the 'length' method, or 'num_elements' if we change to that).  I think this is just a matter of implementing ExprTuple.__getitem__(self, key) and if key is a "slice" you return the result wrapped in ExprTuple.  It should be straightforward.

**Comment by wwitzel** [comment]
Implemented, merged, and tested.
