### ISSUE TITLE
Factor-Finding in Mult.Cancelation() Method

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#228]
Here are two interesting contrasting results obtained when calling the Mult.Cancelation() method on the two numerically-equivalent but differently associated expressions 2 &middot; (&pi; &middot; (1/2)) vs. (2 &middot; &pi;)&middot;(1/2):
![image](https://user-images.githubusercontent.com/41027033/115084865-b27a3a00-9ec6-11eb-9e3b-712f4c9ebe19.png)
In the first case, the algorithm appears to not be finding the 2 in the denominator of the (1/2), because the (1/2) appears only as a (sub-)factor in a larger product (Mult) expression; in the second case, the 2 is discovered in the denominator of the (1/2) because the (1/2) occurs as a factor at the top-level of the expression.

This is not an error but instead the result of an algorithmic choice where we do a shallow search for such factors, and I wonder if it might be useful to implement a modified approach where the search is recursive (or more recursive) — for example, in the first case above, the factors &pi; and (1/2) discovered as sub-factors in the product (&pi; &middot; (1/2)) would be further processed, looking for further Mult or Div objects, which would eventually lead to the discovery of that 2 as a factor in the denominator.

Any eventual code modification, though, would not be trivial — the cancelation() method is already quite complex, and targeted factors discovered with a recursive approach could be embedded in expressions with complex associativity of multiplicands, making it quite complex to perform the desired cancelation and return a canonical equivalent result. It might be that we are better off settling for what we have, and in situations like case 1 shown above the user simply has to manually perform some more modifications first.

**Comment by wwitzel** [comment]
In the "do_reduced_simplification" method (soon to be renamed "shallow_simplification", it goes through an "ungrouping" step (i.e., disassociation).  It then goes on to performing cancelations.  By doing this first, it should resolve the issue.  If that is the case, the issue is only a non-intuitive result when calling the "cancelation" method directly.  If, by default, we do simplifications automatically, this issue shouldn't really come up for a novice user.  It's only when one turns off automatic simplications for whatever reason that it might come up.  To confirm this, does "simplification" work in both cases?

**Comment by wdcraft01** [comment]
@wwitzel Yes: .simplification() works in both cases!

**Comment by wwitzel** [comment]
Do you agree that we can close this issue, then?

**Comment by wdcraft01** [comment]
I also verified that we have the same pattern of results for the more general [a (b c/a)] vs. [(a b) c/a], both in terms of the Mult.cancelations() method (2nd one simplifies, 1st one does not) and the simplification() method (both simplify to bc).
