### ISSUE TITLE
Relabel() Var in the Assumptions of a Known Truth

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#45]
Given a known truth such as `B_from_A = {A, A=>B} |– B`, relabel() attempts such as: `B_from_A.relabel({A:C})` and `B_from_A.relabel({B:C})` fail, producing the following error message in the first (`{A:C}`) case:
`RelabelingFailure: Proof step failed assuming {A, A => B}: Attempting to relabel variable(s) that are free in the assumptions: {A}`
and the following error message in the 2nd (`{B:C}`) case:
`RelabelingFailure: Proof step failed assuming {A, A => B}: Attempting to relabel variable(s) that are free in the assumptions: {B}`
although the relabeling request seems to be perfectly reasonable. The inability to perform such a relabel() might be the inadvertent result of earlier aspects of the `KnownTruth` object and the `KnownTruth` object has evolved since then (Witzel). As illustrated in the tutorial04_relabeling.ipynb notebook at this time (7/15/19), if we convert the assumptions to explicit hypotheses first, then we can do the relabeling that we failed to do before:
`explicit_B_from_A = B_from_A.asImplication(A_impl_B).asImplication(A)`
produces `|– A => ( (A => B) => B)`
which then allows us to relabel: `explicit_B_from_A.relabel({B:C})`
producing `|– A => ( (A => C) => C )`.
We could then apply `deriveConsequent` twice to get back to the original form, now with the relabeled variable:
`explicit_C_from_A.deriveConsequent(assumptions=[A]).deriveConsequent(assumptions=[Implies(A, C)])`
which produces: `{A, A => C} |– C`.
All of which is a long-winded demonstration that, at least in this case, there is no clear reason not to allow the `relabel({B:C})` method to succeed on the original `{A, A => B} |– B` KnownTruth.

**Comment by wwitzel** [comment]
Our current thinking is to allow for a stronger instantiate that implements this feature as a more general replacement (not just relabeling) as well as allowing for the elimination of universal and existential quantifiers (specialize and skolemize).  In addition, we want a separate feature that allows us to relabel within a lambda map.  This does not need to be a derivation step because lambda maps that are equivalent up to parameter relabeling are treated as the same expression in Prove-It now.  But we want a convenient method for changing those lambda parameters.

**Comment by wwitzel** [comment]
What about adding 'instantiate' for doing replacement but keeping 'specialize' for removing a universal quantifier?
That is, instantiation of 'x' would do the following
S |- A
------
S' |- A'
where S' and A' are the same as S and A respectively except that x is replaced.  This is precisely what Deepak has under "Quantifications and Substitutions" is his Prove-It intro write-up.

Specialization, on the other hand would eliminate a universal quantifier (exactly the opposite of generalization).  So its rule is
S |- \forall_{x | S'} A 
-----------------
S union S' |- A
precisely the inverse of the generalization rule that Deepak shows in his write-up.

In practice, the specialize method would perform the specialize step and an instantiation step (and possibly relabeling), but we could internally handle it as separate steps.  Of course, that would make proofs longer and we may not like that, but it is kind of nice to conceptually distinguish the two derivations.  Also, this provides the feature that Hoss was advocating for here -- replacement without having to first generalize.

Regarding relabeling, the kind of relabeling advocated for here would be covered by this new instantiation rule.  Relabeling a Lambda parameter can be done without a derivation step because parameter labels are internally canonized -- changing the parameter label is effectively only a style change.  But relabeling a iterated Lambda parameter is different.  That would be done via an application of the "proveit.logic.equality.mappingSubstitution axiom", so we don't need a separate derivation rule for that.  We'd add a "relabel" method to be used with InnerExpr objects to accomplish both.

**Comment by wdcraft01** [comment]
So, partly playing devil’s advocate here …
(1) We might have to more aggressively ask Bob about this through some other medium — although these comments are sent out via email to participants, he tends to ignore material arriving via email, I'm not sure he can even access his email most of the time. 
(2) It might be that I just need time to "reset" cognitively and get used to the terminology, but my initial reaction to that replacement process being called “instantiation” is “oh no!” Perhaps Bob and Deepak will have some more insight here, but I feel like this would be a challenging re-definition of what most math and coding practitioners mean by “instantiation.” Perhaps a couple concrete examples (hah, perhaps instantiations) might be useful here? If this is really just a substitution or re-labeling, what is the motivation to call it “instantiation”?
— H :o)

**Comment by wwitzel** [comment]
Thanks for some feedback, Hoss.  Note that what I am advocating we call "instantiation" is the rule that Deepak has in the "intro" document draft described as the "specialization/substitution/instantiation" rule.  Perhaps "substitution" is better for this, although we have to distinguish it from the equality-based substitution.  It does seem to make sense to have "specialization" as the inverse of "generalization" though.

**Comment by wwitzel** [comment]
One way to think about it is that you are making a specific/different "instance" of a known truth.  Don't worry, I'm not sold on the terminology yet, and I'll discuss it with Bob first. I'm still struggling with the #102 concepts and haven't quite settled on that yet -- that is more nuanced.

**Comment by wwitzel** [comment]
We can add axioms/theorems for splitting iterated Lambda parameters.  For example,
`\forall_f \forall_{i, j \in Naturals | i <= j+1}`
`[(a_i, ..., a_j, b) |-> f(a_i, ..., a_j, b)] = [(a_i, ..., a_{j+1}) |-> f(a_i, ..., a_{j+1})]`

**Comment by deepakkapur** [comment]
I am fine with Wayne is proposing. 
i need clarification on substitution. 

As you can see, I finally decided to take an account on github.

**Comment by wwitzel** [comment]
Below is my current plan which is a choice to reduce the number of proof steps.  It is subject to change, but something I'll try out and see what y'all think with some demonstrations.

With respect to user interface of the code, 'instantiate' will take over 'specialize' with a broader role.  The existing 'specialize' method can eliminate any number of nested universal quantifiers and then perform a replacement of the corresponding quantified variables (respecting scoping restrictions with respect to internal Lambda maps) as well as simultaneously relabeling internal lambda map parameters.  The 'instantiate' method, as I envision it, will similarly eliminate any number of universal quantifiers but will perform a replacement of *any* free/freed variables (also respecting scoping restrictions and allowing for simultaneous relabeling).  The difference is that this new 'instantiate' allows one to replace 'external' variables (including variables in the assumptions) as well as 'internal' (newly freed) variables.  My intention is for existing calls to 'specialize' to merely change to 'instantiate' and work just as they did before.  It simply allows for things like
{Q(x)} |- P(x)
to transform directly to
{Q(f(x)) |- P(f(x))
without generalizing first.  Why not?

In terms of the write-up in the paper, we may choose to distinguish 'specialization' and 'instantiation' steps.  The 'specialization' step eliminates universal quantifiers.  The 'instantiation' step performs the replacement.  But because these steps typically occur together, we treat them as one 'instantiation' step in practice.

Anyway, we can play with this and discuss it and adapt as necessary.

**Comment by wwitzel** [comment]
One minor thing that may change (for the better) regarding the existing 'specialize' calls (other than changing the name to 'instantiate') is that I plan to nix the explicit 'relabel_map'.  Instead, relabeling can be done implicitly.  If it is a Variable -> Variable map, it can be applied to internal lambda map parameters.  If it maps a Variable to a non-Variable expression, the replacement does NOT reach inside internal lambda maps with a parameter that happens to be the same as that Variable.  It is treated in a Variable in a new scope.  The motivation of this change is to simplify the interface.  We can adjust it after we discuss it.  But I'd like to charge ahead with something that I can demonstrate and then we can discuss it.

**Comment by wwitzel** [comment]
This is being handled with new "instantiate" method.
