### ISSUE TITLE
Provide deduceInBool() method in NumberMembership and InSet

### ISSUE THREAD

**Issue by wdcraft01** [PyProveIt/Prove-It#59]
The NumberMembership class is defined in
    `proveit/number/sets/number_set.py`
The InSet Operation class is defined in
    `proveit/logic/set_theory/membership/in_set.py`
Related issues arose recently (9/20/2019) when working on a proof of the
irrationality of Sqrt(2), where the proof conclusion appeared in the form of
`(sqrt(2) \in Q) ≠ T`
instead of a more straightforward form such as `sqrt(2) \not\in Q`.

**Comment by wdcraft01** [comment]
Updated the logic/set_theory/membership ``InSet`` class to have a ``deduceInBool()`` method (modeled on the ``deduceInBool()`` method existing in the logic/equality ``Equals`` class), and added a corresponding axiom (called ``membershipInBool``) to the membership axioms ipynb notebook. Tested this briefly in the membership demonstrations notebook, which I will also update while I'm working in the issue#59 branch.

**Comment by wdcraft01** [comment]
Interesting discovery: the `NotInSet` class already had a `deduceInBool()` method, along with the following definition and accompanying comment (probably from Wayne):

>    def deduceInBool(self):
        '''
        Deduce and return that this 'not in' statement is in the set of BOOLEANS.
        PERHAPS MEMBERSHIP/NON-MEMBERSHIP SHOULD ALWAYS BE IN BOOLEAN, THOUGH
        ILL-DEFINED DOMAINS CAN NEVER HAVE MEMBERSHIP TO BE TRUE -- REVISIT.
        '''
        self.domain.deduceNotInSetIsBool(self.element)

And trying to call `deduceInBool()` on a simple example such as `NotInSet(a, A)`, where A (the domain) is just a variable, immediately raises an error because a variable does not have a `deduceNotInSetIsBool()` method. My plan is to comment out the current definition and proceed analogous to the `InSet` method (which itself I've based on the model established for equality).

**Comment by wwitzel** [comment]
“membershipInBool” should NOT be an axiom!  I understand that this was modeled after equalityInBool.  That was okay for equality, but having “membershipInBool” as an axiom will enable Russel’s paradox in the way that we have things set up.  That is, we are using whether or not membership can be proven to be in Booleans to dictate whether something is a set or not.  We may want to debate alternative ways to do this, but let’s not break what we currently have.

**Comment by wwitzel** [comment]
That comment in NonInSet.deduceInBool is a bit stale.  To avoid Russel's paradox (in the current approach), we must only allow (x \in S) to be a Boolean if S is a valid defined set.  For (x \nin S), we probably want to add the following theorem which should be easy to prove:
\forall_{x, S | (x \in S) \in Booleans} (x \nin S) \in Booleans.

**Comment by wwitzel** [comment]
The proper way to treat InSet.deduceInBool is to add a "deduceInBool" method to the Membership class (defined within in_set.py) with the default raising a NotImplementedError.  InSet.deduceInBool should call deduceInBool on its membershipObject (if it has one -- if not, raise an appropriate error).  Classes derived from Membership should implement deduceInBool as appropriate, usually calling a theorem that essentially proves that something is a set.  This could, and probably should, be done in BooleanMembership, with a theorem stating: \forall_{x} [(x \in Booleans) \in Booleans].  That should not be hard to prove (given the definition of Booleans as an enumerated set and using proveit.logic.set_theore.enumeration.enumSetDef).  This should also be done for each number set (integers, reals, etc.).  They should all have theorems to prove things of the form:
\forall_{x} [(x \in N) \in Booleans].
Essentially, this is proving that the number set is a properly-defined set.  Note that in the Naturals case, this does follow from naturalsDef since (x \in Naturals) is equated to a universal quantification and universal quantification are all Booleans (via an axiom).
The NumberMembership class should implement "deduceInBool" which should call "deduceMembershipInBool" on its 'number_set'.  Then each particular class derived from NumberSet should implement "deduceMembershipInBool" which should invoke the appropriate theorem.

To address your question about how NumberSet's work, you will find various examples: IntegersSet and NaturalsSet are in proveit.number.sets.integer, RealsSet is in proveit.number.sets.reals, etc.  These define classes for a Literal which will each only have one instance.  This instance is created in _common_.ipynb notebooks in the respective packages.

The NumberMembership class provides an interface between InSet and NumberSet's.  NumberSet has a "membershipObject" method an InSet object may call to get access to methods that deal with membership within its particular domain.  For example, if you have an (x in Naturals) object, which is an InSet object, it can get access the appropriate Membership object to know how to deal with things like "deduceInBool" for that specific domain.

Hope this helps.

**Comment by wwitzel** [comment]
Note, when calling "deduceMemberInBool" from NumberMembership.deduceInBool, you'll want to pass along the "element".  That is, call it on the domain ("number_set") but let it know the element you are dealing with.

**Comment by wdcraft01** [comment]
> That comment in NonInSet.deduceInBool is a bit stale. To avoid Russel's paradox (in the current approach), we must only allow (x \in S) to be a Boolean if S is a valid defined set. For (x \nin S), we probably want to add the following theorem which should be easy to prove:
> \forall_{x, S | (x \in S) \in Booleans} (x \nin S) \in Booleans.

OK, I have added that theorem and proven it. Somewhat sadly, the theorem is called ``notInSetInBoolIfInSetInBool``. Suggestions for a more concise but informative name would be most welcome. I have also removed the evil ``membershipInBool`` axiom and related ``notInSetInBool`` theorem. Now looking more carefully at the rest of your comments.

**Comment by wwitzel** [comment]
Very good.  Hmm... naming things can be tough.  I would shorten it to `notInSetInBool`.  There should not be an ambiguity problem since that is the one obvious way to generally prove that a NotInSet expression is in the Boolean set.

**Comment by wwitzel** [comment]
Merged into master from "Issue#59 craft".
